### ISSUE TITLE
Unable to find IMDb URL

### ISSUE THREAD

**Issue by jefro108** [ctlaltdefeat/mpv-open-imdb-page#1]
Whatever file I try I get "Unable to find IMDb URL" eg 'Seven Worlds One Planet.s01e07.Africa.mp4' 
Using guessit on the file shows that the information is parsed ok
`    "title": "Seven Worlds One Planet",
    "season": 1,
    "episode": 7,
    "episode_title": "Africa",
    "container": "mp4",
    "mimetype": "video/mp4",
    "type": "episode"`

**Comment by ctlaltdefeat** [comment]
What happens if you run the Python script directly with the name of the file?
```
python .../open-imdb-page.py "Seven Worlds One Planet.s01e07.Africa.mp4"
```

**Comment by jefro108** [comment]
When I run the python script as you suggest it opens the correct IMDb page! 
But the ctl-i key combination still produces the  "Unable to find IMDb URL" message 😞

**Comment by ctlaltdefeat** [comment]
So I'd imagine that the script is unable to find either the python binary or the correct python script location.
Try changing the following line in the ```.lua``` script:
```
table.args = {"python", script_dir.."open-imdb-page.py", mp.get_property("filename")}
```
to point to the full paths, so something like the following for Windows:
```
table.args = {"C:\\Python\\python.exe", "C:\\mpv\\scripts\\open-imdb-page.py", mp.get_property("filename")}
```
or something like the following for Unix:
```
table.args = {"/usr/bin/python", "/home/blah/..../scripts/open-imdb-page.py", mp.get_property("filename")}
```

**Comment by jefro108** [comment]
I’m on MacOS . When I use
   
`table.args = {"/usr/bin/python", "~/.config/mpv/script/open-imdb-page.py", mp.get_property("filename")}`

I still get the message "Unable to find IMDb URL" 😞

**Comment by jefro108** [comment]
FWIW I see that https://github.com/zenyd/mpv-scripts has a more involved way of invoking the python script

**Comment by ctlaltdefeat** [comment]
I imagine that lua doesn't do shell expansion for ```~/``` and so that's the current problem; if you write out the full path it should work.

However, I expected the original line to properly locate the python script file automatically. It does so on my Windows and Linux machines that I have. Once you've confirmed it works with the full path, could you please try reverting to the original line, launching mpv with logging enabled to a log file - ```mpv --log-file=log.txt```, and then uploading said log file somewhere so I can take a look? Thanks

**Comment by jefro108** [comment]
Sorry for the delay in replying. I was away for the weekend.

It works with the full path in the command line, of course. But with the full path in the .lua file it still comes up with the error when pressing ctl-i.

I tried to launch mpv with logging enabled but the version I have doesn't seem to have the logging option available.

```
$mpv --log-file=log.txt
mpv 0.30.0 Copyright © 2000-2019 mpv/MPlayer/mplayer2 projects
 built on Sun Nov  3 20:28:56 CET 2019
ffmpeg library versions:
   libavutil       56.31.100
   libavcodec      58.54.100
   libavformat     58.29.100
   libswscale      5.5.100
   libavfilter     7.57.100
   libswresample   3.5.100
ffmpeg version: 4.2.1

Usage:   mpv [options] [url|path/]filename

Basic options:
 --start=<time>    seek to given (percent, seconds, or hh:mm:ss) position
 --no-audio        do not play sound
 --no-video        do not play video
 --fs              fullscreen playback
 --sub-file=<file> specify subtitle file to use
 --playlist=<file> specify playlist file

 --list-options    list all mpv options
 --h=<string>      print options which contain the given string in their name
```

**Comment by ctlaltdefeat** [comment]
Hey, so it looks like what's happening is that the python that mpv runs does not have the modules installed.

Do you have multiple versions of python installed (say python 2 and 3)? You have to make sure that the python binary that works successfully in the command line is the one used in the script, so run ```which python``` in the command line to figure out the path and then input that into the lua

**Comment by jefro108** [comment]
Great, thanks.

Putting in `"/usr/local/opt/python/libexec/bin/python"` in the lua script instead of `"python"` did the trick, which I got from `which python`
```
$ python
Python 3.7.5 (default, Nov  1 2019, 02:16:32) 
[Clang 11.0.0 (clang-1100.0.33.8)] on darwin
```
is what I get when I run python without any arguments. I may have installed python 3 in homebrew for something or other - I forget now.
